### ISSUE TITLE
extension needs to be updated to include fixes in CRM-17022

### ISSUE THREAD

**Issue by rpamfil** [JMAConsulting/biz.jmaconsulting.grantapplications#121]
When the extension is enabled, searching for grants with a filter for grant type, causes a DB error.
See stack trace below.
The fix for this is in the latest version of CiviCRM:
https://issues.civicrm.org/jira/browse/CRM-17022
```
#0 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(360): CRM_Core_Error::backtrace()
#1 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Utils/Type.php(262): CRM_Core_Error::fatal("(1) is not of the type Integer")
#2 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Contact/BAO/Query.php(5207): CRM_Utils_Type::escape("(1)", "Integer")
#3 /data/www/website.org/wp-content/plugins/civicrm/custom_ext/biz.jmaconsulting.grantapplications-4.6/CRM/Grant/BAO/Query.php(216): CRM_Contact_BAO_Query::buildClause("civicrm_grant.grant_type_id", "IN", "(1)", "Integer")
#4 /data/www/website.org/wp-content/plugins/civicrm/custom_ext/biz.jmaconsulting.grantapplications-4.6/CRM/Grant/BAO/Query.php(115): CRM_Grant_BAO_Query::whereClauseSingle((Array:5), Object(CRM_Contact_BAO_Query))
#5 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Core/Component.php(315): CRM_Grant_BAO_Query::where(Object(CRM_Contact_BAO_Query))
#6 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Contact/BAO/Query.php(1877): CRM_Core_Component::alterQuery(Object(CRM_Contact_BAO_Query), "where")
#7 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Contact/BAO/Query.php(499): CRM_Contact_BAO_Query->whereClause()
#8 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Contact/BAO/Query.php(461): CRM_Contact_BAO_Query->initialize()
#9 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Grant/Selector/Search.php(168): CRM_Contact_BAO_Query->__construct((Array:3), NULL, NULL, FALSE, FALSE, 128)
#10 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Grant/Form/Search.php(244): CRM_Grant_Selector_Search->__construct((Array:3), 1, NULL, FALSE, NULL, "search")
#11 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(345): CRM_Grant_Form_Search->postProcess()
#12 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Refresh.php(75): CRM_Core_Form->mainProcess()
#13 /data/www/website.org/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Refresh->perform(Object(CRM_Grant_Form_Search), "refresh")
#14 /data/www/website.org/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Grant_Form_Search), "refresh")
#15 /data/www/website.org/wp-content/plugins/civicrm/custom_ext/biz.jmaconsulting.grantapplications-4.6/CRM/Core/Controller.php(359): HTML_QuickForm_Page->handle("refresh")
#16 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(312): CRM_Core_Controller->run((Array:3), NULL)
#17 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:14))
#18 /data/www/website.org/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#19 /data/www/website.org/wp-content/plugins/civicrm/civicrm.php(1189): CRM_Core_Invoke::invoke((Array:3))
#20 [internal function](): CiviCRM_For_WordPress->invoke("")
#21 /data/www/website.org/wp-includes/plugin.php(503): call_user_func_array((Array:2), (Array:1))
#22 /data/www/website.org/wp-admin/admin.php(236): do_action("toplevel_page_CiviCRM")
```

**Comment by JoeMurray** [comment]
Thanks, rpamfil. Which version of the extension were you using when you got this error?

**Comment by rpamfil** [comment]
v1.4.1.

**Comment by Edzelopez** [comment]
This is now included.

**Comment by robbrandt** [comment]
Hi.  This is happening on our CiviCRM 4.6.9 install with v 4.2 of this extension.  Is there a something I could do to backport this?  I don't see a commit associated with this issue.  We hope to avoid doing an update on the site until December.

**Comment by Edzelopez** [comment]
Hi @robbrandt 

This has been fixed in v1.4.4 version of the extension. Please update it by downloading the extension from here: https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/releases/tag/v1.4.4

Thanks,
Edsel

**Comment by robbrandt** [comment]
Thanks.  For some reason I thought that was for 4.7 only.  I see now it's OK for 4.6.  I'll try it tomorrow.

**Comment by robbrandt** [comment]
FYI, this release presents itself as 1.4.2 in the UI.  Confusing about what version I was running until I checked the code:
https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/blob/v1.4.4/info.xml

**Comment by Edzelopez** [comment]
Thanks! I'll update that ASAP.
