### ISSUE TITLE
Uncaught Error: Class 'CRM_Grant_BAO_Grant' 

### ISSUE THREAD

**Issue by adam-devapp** [JMAConsulting/biz.jmaconsulting.grantapplications#184]
Getting this error when running the 5.50.1 upgrader. The upgrade page won't load without the extension being disabled.

```
Fatal error: Uncaught Error: Class 'CRM_Grant_BAO_Grant' not found in /home/xxxx/public_html/wp-content/uploads/civicrm/ext/biz.jmaconsulting.grantapplications/CRM/Grant/BAO/Query.php:22 Stack trace: #0 /home/xxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Component.php(244): CRM_Grant_BAO_Query::getFields(false) #1 /home/xxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Contact/BAO/Query.php(508): CRM_Core_Component::getQueryFields(false) #2 /home/xxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Contact/BAO/Query.php(4603): CRM_Contact_BAO_Query->__construct(Array, NULL, NULL, true, false, 1, 1, true, NULL, NULL, 'AND', 'Contact', true) #3 /home/xxxx/public_html/wp-content/plugins/civicrm/civicrm/api/v3/utils.php(586): CRM_Contact_BAO_Query::apiQuery(Array, NULL, NULL, NULL, 0, '0', NULL, NULL, 1, 1, 'Contact', true) #4 /home/xxxx/public_html/wp-content/plugins/civicrm/civicrm/api/v3/Contact.php(162): _civicrm_api3_get_using_query_object('Contact', Array, Array) #5 /home/xxxx/public_html/ in /home/xxxx/public_html/wp-content/uploads/civicrm/ext/biz.jmaconsulting.grantapplications/CRM/Grant/BAO/Query.php on line 22
```

**Comment by adam-devapp** [comment]
I had to disable the grant extension, then upgrade CiviCRM, then re-enable the grant extension and the error is no longer appearing..

**Comment by adam-devapp** [comment]
Also when viewing the contact dashboard (wordpress widget showing user dashboard) on the front end of the site:

```
Fatal error: Uncaught Error: Call to a member function getUserDashboardObject() on null in /home/xxxx/public_html/wp-content/uploads/civicrm/ext/biz.jmaconsulting.grantapplications/grantapplications.php:376 Stack trace: #0 /home/xxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(271): grantapplications_civicrm_pageRun(Object(CRM_Contact_Page_View_UserDashBoard)) #1 /home/xxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(136): CRM_Utils_Hook->runHooks(Array, 'civicrm_pageRun', 1, Object(CRM_Contact_Page_View_UserDashBoard), NULL, NULL, NULL, NULL, NULL) #2 /home/xxxx/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(237): CRM_Utils_Hook_WordPress->invokeViaUF(1, Object(CRM_Contact_Page_View_UserDashBoard), NULL, NULL, NULL, NULL, NULL, 'civicrm_pageRun') #3 /home/xxxx/public_html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\ in /home/xxxx/public_html/wp-content/uploads/civicrm/ext/biz.jmaconsulting.grantapplications/grantapplications.php on line 376
```

**Comment by monishdeb** [comment]
Ok checking now !!

**Comment by monishdeb** [comment]
@adam-devapp can you please try the PR https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/pull/185 ? 


The issue occurred because of:
1. extension override the core file `CRM_Grant_BAO_Query` that is no longer required
2. core dropped the CiviGrant info file and moved all the components function to civigrant hooks (commit - https://github.com/civicrm/civicrm-core/pull/22064/commits/be49cd8a5ebde959e12939bac5d03056894b44c5) except `getUserDashboardObject` .  Made changes accordingly.

**Comment by monishdeb** [comment]
@adam-devapp did you get a chance to review the patch #185 ?

**Comment by adam-devapp** [comment]
Hi @monishdeb Waiting on approval from client to apply/test it. Will update again once tested.

**Comment by monishdeb** [comment]
Moved to https://lab.civicrm.org/extensions/grantapplications/-/issues/184
